= PHP Reflect

**PHP Reflect** is a library that
adds the ability to reverse-engineer classes, interfaces, functions, constants, namespaces, traits and more.


Both were distributed as source code (install via composer) and a PHAR version
that bundles all dependencies in a single file.

Follow development on the http://php5.laurent-laville.org/reflect/blog/[official Blog].

Have a look on https://github.com/llaville/php-reflect/releases/tag/2.6.2[tag 2.6.2] for previous stable API 2.0

== Install

You can either :

* download the phar version http://bartlett.laurent-laville.org/get/phpreflect-3.0.1.phar[3.0.1]
* install via https://packagist.org/packages/bartlett/php-reflect/[packagist] the current source dev-master or the stable version 3.0.1

== Documentation

The documentation for PHP Reflect 3.0 is available
in http://php5.laurent-laville.org/reflect/manual/3.0/en/[English]
to read it online or download to read it later (multiple formats).

AsciiDoc source code are available on `docs` folder of the repository.

== Contribute

Contributions to source code and its documentation are always welcome.

As developper, I'm always happy when I have the more informations as possible to check and find out issues.
This is the reason why I've created a https://github.com/llaville/phpunit-LoggerTestListener[PHPUnit TestSuite Listener for compatible PSR-3 Loggers].

If you want to use it, then :

- install the component via Composer

[source,bash]
----
$ php composer.phar require bartlett/phpunit-loggertestlistener=~1.3
----

- create a `phpunit.xml` file with at least following contents :

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<phpunit
    backupGlobals="true"
    backupStaticAttributes="false"
    bootstrap="tests/bootstrap.dev.php"
    colors="false"
    stopOnError="false"
    stopOnFailure="false"
    stopOnIncomplete="false"
    stopOnRisky="false"
    stopOnSkipped="false"
    verbose="false"
>
    <filter>
        <whitelist>
        <directory suffix=".php">src/</directory>
        </whitelist>
    </filter>
    <listeners>
        <listener class="Bartlett\LoggerTestListener">
            <arguments>
                <object class="Psr3Logger" />
            </arguments>
        </listener>
    </listeners>
    <testsuites>
        <testsuite name="Reflect Test Suite">
            <directory suffix="Test.php">tests/</directory>
        </testsuite>
    </testsuites>
</phpunit>
----

- configure your PSR-3 logger in the `tests\bootstrap.dev.php` file

NOTE: Default will log all tests in local file `/var/logs/phpreflect.log`
and send a Growl notification of Test Suites summary when ended (if growl server running).
