= PHP Reflect

**PHP Reflect** is a library that
adds the ability to reverse-engineer classes, interfaces, functions, constants, namespaces, traits and more.


Both were distributed as source code (install via composer) and a PHAR version
that bundles all dependencies in a single file.

Follow development on the http://php5.laurent-laville.org/reflect/blog/[official Blog].

Have a look on https://github.com/llaville/php-reflect/tree/3.1[branch 3.1] for previous stable API 3.1

== Install

You can either :

* download the phar version http://bartlett.laurent-laville.org/get/phpreflect-4.0.0.phar[4.0.0]
* install via https://packagist.org/packages/bartlett/php-reflect/[packagist] the current source dev-master or the stable version 4.0.0

== Documentation

The documentation for PHP Reflect 4.0 is available
in http://php5.laurent-laville.org/reflect/manual/4.0/en/[English]
to read it online or download to read it later (multiple formats).

AsciiDoc source code are available on `docs` folder of the repository.

== Authors

* Laurent Laville

== License

This handler is licensed under the BSD-3-clauses License - see the `LICENSE` file for details
