= PHP Reflect

**PHP Reflect** is a library that
adds the ability to reverse-engineer classes, interfaces, functions, constants, namespaces, traits and more.


Both were distributed as source code (install via composer) and a PHAR version
that bundles all dependencies in a single file.

== Requirements

PHP 5.6.0 or above.

== Install

You can either :

* download the phar version http://bartlett.laurent-laville.org/get/phpreflect-4.3.0.phar[4.3.0]
* install via https://packagist.org/packages/bartlett/php-reflect/[packagist] the current source dev-master

== Documentation

The documentation for PHP Reflect 4.2 is available
in http://php5.laurent-laville.org/reflect/manual/4.2/en/[English]
to read it online or download to read it later (multiple formats).

AsciiDoc source code are available on `docs` folder of the repository.

== Authors

* Laurent Laville
* Thanks to Nikita Popov who wrote a marvellous https://github.com/nikic/PHP-Parser[PHP Parser] and simplify the job of PHP Reflect.
* Thanks also to Remi Collet, a contributor of first hours.

== License

This handler is licensed under the BSD-3-clauses License - see the `LICENSE` file for details
