= PHP Reflect

**PHP Reflect** is a library that
adds the ability to reverse-engineer classes, interfaces, functions, constants, namespaces and more.


== Blog

* The first mature Release Candidate (RC2) of API 2.0 was released Tue, 18 Feb 2014.
* The last Release Candidate (RC3) of API 2.0 was released Fri, 24 Mar 2014.
* Final stable release is planned for Fri, 4 Apr 2014.

Both were distributed as source code (install via composer) and a PHAR version
that bundles all dependencies in a single file.

Follow development on the http://php5.laurent-laville.org/reflect/blog/[official Blog].

Have a look on master branch for previous stable API 1.0

== Install

You can either :

* download the phar version http://bartlett.laurent-laville.org/get/phpreflect-2.0.0RC2-6-ge55464a.phar[2.0.0RC2]
* download the phar version http://bartlett.laurent-laville.org/get/phpreflect-2.0.0RC3.phar[2.0.0RC3]
* install via https://packagist.org/packages/bartlett/php-reflect/[packagist] the current source 2.x-dev or the 2.0.0RC3

== Documentation

The documentation for PHP Reflect will be soon available
in http://php5.laurent-laville.org/reflect/manual/2.0/en/[English]
and different formats, begun with a web doc,
built with https://github.com/llaville/asciidoc-bootstrap-backend[AsciiDoc-Bootstrap]
and http://getbootstrap.com/[Bootstrap 3].

AsciiDoc source code are available on `docs` folder of the repository.
