:css-signature: blog
:icons!:
:iconsfont: font-awesome
:iconsfontdir: ./fonts/font-awesome
:imagesdir: ./images
:author: Laurent Laville
:revdate: 2014-02-12
:pubdate: Wed, 12 Feb 2014 14:40:53 +0100
:summary: A new parser for Reflect 2.0.0RC2

== Future release 2.0.0RC2 will adopt PHP-Parser

[role="blog",cols="3,9",halign="right",citetitle="Published by {author} on {revdate}"]
.icon:clock-o[size="4x"]
--
[role="lead"]
{summary}

Two weeks ago, I've detected performance issues with the core of Reflect parser.
I've then begun to rewrite the core of the parser, and now I don't like it.

It's not enough stable, and I don't want to loose my time to test all conditions.

So, that this the reason why I've adopted yesterday a new external parser written in PHP :
https://github.com/nikic/PHP-Parser[PHP-Parser]. This parser is awesome and fast.
Easy to understand how to implement (uses visitors design and an
http://en.wikipedia.org/wiki/Abstract_syntax_tree[Abstract Syntax Tree] (AST)).

I've migrated in one day my code to use this new parser, and I've begin this morning to test it in real condition.

I should publish the latest version of my source code tomorrow.

It sound nice to me that *the second release candidate will be available this monday 17th February*.  
--
