= Getting Started
:description: How to download, configure and use it in a basic way.
include::revision.asciidoc[]
include::attributes.asciidoc[]
:pharstable:  http://bartlett.laurent-laville.org/get/phpreflect-4.1.0.phar


== Download

We distribute a http://www.php.net/phar[PHP Archive] (PHAR) that contains
all required dependencies of PHP [label label-primary]#Reflect# bundled in a single file.

ifdef::basebackend-bootstrap[]
link:{pharstable}["Download the latest version",role="primary",icon="glyphicon-download-alt",options="block,white"]
endif::basebackend-bootstrap[]
ifndef::basebackend-bootstrap[]
link:{pharstable}[Download the latest version]
endif::basebackend-bootstrap[]

Make it executable, and put it into your `$PATH`.
[source,bash]
----
$ chmod +x phpreflect-4.1.0.phar
$ mv phpreflect-4.1.0.phar /usr/local/bin/phpreflect

$ phpreflect --version
----

You can also immediately use the PHAR after you have downloaded it.
[source,bash]
----
$ wget http://bartlett.laurent-laville.org/get/phpreflect-4.1.0.phar
$ php phpreflect-4.1.0.phar --version
----

With both methods then you have this output :

[role="output"]
====
----
phpReflect version 4.1.0
----
====

Other alternative installations are possible.
Please refer to the
ifdef::basebackend-html[]
link:user-guide&#45;&#45;installation.html[documentation]
endif::basebackend-html[]
ifdef::basebackend-docbook[]
xref:_installation[]
endif::basebackend-docbook[]
for details on how to do this.

[role="col-md-6"]
== Configuration
[source,json]
.With the minimalist JSON file +phpreflect.json+
----
{
    "source-providers": [
        {
            "in": ". as current",
            "name": "/\\.(php|inc|phtml)$/"
        }
    ],
    "plugins": [
    ],
    "analysers": [
    ],
    "services": [
    ]
}
----
Put it in your project's folder. Alternative locations are possible.
Please refer to the
ifdef::basebackend-html[]
link:user-guide&#45;&#45;configuration.html[documentation]
endif::basebackend-html[]
ifdef::basebackend-docbook[]
xref:_the_json_configuration_file[]
endif::basebackend-docbook[]
for details on how to do this.

NOTE: The JSON configuration file is no more required for basic usage.
Reserved to advanced users.

[role="col-md-6"]
== Structure

source-providers::
this entry provide list of your data sources to parse.

plugins::
this entry list all plugins added to the core base code of PHP Reflect.

analysers::
this entry list all analysers that may be used with the `analyser:run` command.

services::
this entry list all services that may be used with this application.

[role="col-md-12 clearfix"]
== Execution

With the
[label label-primary]#Reflect# source code, invoke the following command :
[source,bash]
----
$ phpreflect analyser:run .
----
and you should obtain something like this :

[role="output"]
====
----
include::structure_analysis.out.asciidoc[]
----
====

Another analyser (`loc`) is also available, and can be combined or not with `structure`
the default analyser.

With the
[label label-primary]#Reflect# source code, invoke the following command :
[source,bash]
----
$ phpreflect analyser:run . loc
----
and you should obtain something like this :

[role="output"]
====
----
include::loc_analysis.out.asciidoc[]
----
====


== Summary

[role="lead"]
Let's review what we've done :

* downloaded the latest stable PHAR version.
* prepared a minimalist JSON configuration file that is OPTIONAL to run [label label-primary]#Reflect# commands.
* executed your first parse on the [label label-primary]#Reflect# data source.

== Next

[role="lead"]
Choose your way depending of your skill level.

************************************************
.Read more

* Want to learn more about the command line interpreter (CLI) version, interface that do
[label label-primary]#Reflect# an easy tool without to write a line of PHP code,
have a look on
ifdef::basebackend-html[]
link:user-guide.html[user's guide]
endif::basebackend-html[]
ifdef::basebackend-docbook[]
xref:_user_guide[]
endif::basebackend-docbook[]

* Want to learn more about [label label-primary]#Reflect# architecture and /or
you want to extends it to match your needs,
have a look on
ifdef::basebackend-html[]
link:developer-guide.html[developer's guide]
endif::basebackend-html[]
ifdef::basebackend-docbook[]
xref:_developer_guide[]
endif::basebackend-docbook[]

* You are a user of previous version 1.9 that is really different, and want to
upgrade to the new major version 2, and keep your old environment still running,
have a look on
ifdef::basebackend-html[]
link:migration-guide-30.html[migration's guide]
endif::basebackend-html[]
ifdef::basebackend-docbook[]
xref:_migration_guide_30[]
endif::basebackend-docbook[]

************************************************
