= Getting Started
:description: How to download, configure and use it in a basic way.
include::revision.asciidoc[]
include::attributes.asciidoc[]
:icons!:
:iconsfont:   font-awesome
:jumbotron:
:jumbotron-fullwidth:
:footer:
:footer-fullwidth:
:pharstable:  http://bartlett.laurent-laville.org/get/phpreflect.phar


== Download

We distribute a http://www.php.net/phar[PHP Archive] (PHAR) that contains
all required dependencies of PHP [label label-primary]#Reflect# bundled in a single file.

ifdef::basebackend-bootstrap[]
link:{pharstable}["Download the latest version",role="primary",icon="glyphicon-download-alt",options="block,white"]
endif::[]
ifndef::basebackend-bootstrap[]
link:{pharstable}[Download the latest version]
endif::[]

Make it executable, and put it into your `$PATH`.
----
$ chmod +x phpreflect.phar
$ mv phpreflect.phar /usr/local/bin/phpreflect

$ phpreflect --version
----

You can also immediately use the PHAR after you have downloaded it.
----
$ wget http://bartlett.laurent-laville.org/get/phpreflect.phar
$ php phpreflect.phar --version
----

With both methods then you have this output :

[role="cli-output"]
====
----
phpReflect version 2.0.0 build b45be1d0d1b5a46253f9cda894dd7717f0a64abd
----
====

Other alternative installations are possible.
Please refer to the link:user-guide&#45;&#45;installation.html[documentation] for details on how to do this.

[role="col-md-6"]
== Configuration
.With the minimalist JSON file +phpreflect.json+
----
{
    "source-providers": [
        {
            "in": ". as current",
            "name": "/\\.(php|inc|phtml)$/"
        }
    ],
    "plugins": [
        {
            "name": "Analyser",
            "class": "Bartlett\\Reflect\\Plugin\\Analyser\\AnalyserPlugin"
        }
    ],
    "analysers" : [
        {
            "name": "Structure",
            "class": "Bartlett\\Reflect\\Analyser\\StructureAnalyser"
        }
    ]
}
----
Put it in your project's folder. Alternative locations are possible.
Please refer to the link:user-guide&#45;&#45;configuration.html[documentation] for details on how to do this.


[role="col-md-6"]
== Structure

source-providers::
this entry provide list of your data sources to parse.
+
[TIP]
====
Like [label label-primary]#Reflect# always needs a JSON file to run, Remi Collet
https://github.com/llaville/php-compat-info/issues/120#issuecomment-46188900[shared]
a workaround solution exposed here that allows to run :
----
$ phpreflect analyser:run .
----
====

plugins::
this entry list all plugins added to the core base code of PHP Reflect.
+
CAUTION: Don't forget to add at least this default content, else the `analyser:run`
and `analyser:list` commands wouldn't be available.

analysers::
this entry list all analysers that may be used with the `analyser:run` command.
+
IMPORTANT: Don't miss it, else you could not run the `analyser:run` command.

[role="col-md-12 clearfix"]
== Execution

With a default +phpreflect.json+ as detailed above, put in the +src/+ folder of the
[label label-primary]#Reflect# source code, and invoke the following command :
----
$ phpreflect analyser:run .
----
and you should obtain something like this :

[role="cli-output"]
====
----
include::structure_analysis.out.asciidoc[]
----
====


== Summary

[role="lead"]
Let's review what we've done :

* downloaded the latest stable PHAR version.
* prepared your JSON configuration file that is required to run [label label-primary]#Reflect# commands.
* executed your first parse on the [label label-primary]#Reflect# data source.

== Next

[role="lead"]
Choose your way depending of your skill level.

************************************************
.Read more

* Want to learn more about the command line interpreter (CLI) version, interface that do
[label label-primary]#Reflect# an easy tool without to write a line of PHP code,
have a look on link:user-guide.html[user's guide].

* Want to learn more about [label label-primary]#Reflect# architecture and /or
you want to extends it to match your needs,
have a look on link:developer-guide.html[developer's guide].

* You are a user of previous version 1.9 that is really different, and want to
upgrade to the new major version 2, and keep your old environment still running,
have a look on link:migration-guide.html[migration's guide].
************************************************
